Repository jenkins-x-charts/jxboot-resources, pull requests merged in 2019-10, with the labels that each got.

#6 fix: allow the environments to be configured remote
  jxboot-resources/templates/production-env.yaml
  jxboot-resources/templates/staging-env.yaml
  jxboot-resources/values.yaml
Labels: size/XS

#8 feat: added ability to configure gitPublic in dev-env
  jxboot-resources/templates/dev-env.yaml
  jxboot-resources/values.yaml
Labels: approved, size/XS

#9 feat: add the capability to configure exposer
  jxboot-resources/templates/ingress-config-configmap.yaml
  jxboot-resources/values.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#10 feat: disable the github pipeline secret when vault is enabled
  jxboot-resources/templates/gh-secret.yaml
  jxboot-resources/values.yaml
Labels: approved, lgtm, size/XS

#11 chore: add updatebot support to env repos
  jxboot-resources/templates/env-scheduler.yaml
Labels: approved, lgtm, size/S
