Repository jenkins-x-charts/jxboot-resources, pull requests merged in 2020-01, with the labels that each got.

#18 feat: Make locations of build pack and quickstarts configurable
  jxboot-resources/templates/dev-env.yaml
  jxboot-resources/values.yaml
Labels: approved, lgtm, ok-to-test, size/S

#20 feat: Make production and staging namespaces configurable
  jxboot-resources/templates/production-env.yaml
  jxboot-resources/templates/staging-env.yaml
  jxboot-resources/values.yaml
Labels: approved, lgtm, ok-to-test, size/S

#21 fix: Default namespace for staging env should be staging, not production
  jxboot-resources/templates/staging-env.yaml
Labels: approved, size/XS

#17 feat: Add annotation to the ingress objects
  jxboot-resources/templates/700-bucketrepo-ing.yaml
  jxboot-resources/templates/700-chartmuseum-ing.yaml
  jxboot-resources/templates/700-deck-ing.yaml
  jxboot-resources/templates/700-docker-ing.yaml
  jxboot-resources/templates/700-hook-ing.yaml
  jxboot-resources/templates/700-jenkins-ing.yaml
  jxboot-resources/templates/700-nexus-ing.yaml
  jxboot-resources/templates/700-tide-ing.yaml
  jxboot-resources/values.yaml
Labels: approved, ok-to-test, size/S

#22 fix: environment repo SourceRepository names should be lower-case
  jxboot-resources/templates/dev-repo.yaml
  jxboot-resources/templates/production-repo.yaml
  jxboot-resources/templates/staging-repo.yaml
Labels: approved, lgtm, size/XS

#23 chore: add missing upgrade cronjob template
  jxboot-resources/templates/upgrade-cj.yaml
  jxboot-resources/values.yaml
Labels: approved, lgtm, size/M

#24 fix: add release only + PR only schedulers
  jxboot-resources/templates/pr-only-scheduler.yaml
  jxboot-resources/templates/release-only-scheduler.yaml
Labels: size/L

#26 fix: Dev env URLs should be set in SourceRepository
  jxboot-resources/templates/dev-repo.yaml
Labels: approved, lgtm, size/XS
