Repository jenkins-x-charts/jxboot-resources, pull requests merged in 2020-04, with the labels that each got.

#35 fix: use the correct key for remoteCluster on environments
  jxboot-resources/templates/production-env.yaml
  jxboot-resources/templates/staging-env.yaml
Labels: approved, lgtm, size/XS

#36 Update OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#32 fix: different tls secret per ingress
  jxboot-resources/templates/700-bucketrepo-ing.yaml
  jxboot-resources/templates/700-chartmuseum-ing.yaml
  jxboot-resources/templates/700-deck-ing.yaml
  jxboot-resources/templates/700-docker-ing.yaml
  jxboot-resources/templates/700-hook-ing.yaml
  jxboot-resources/templates/700-jenkins-ing.yaml
  jxboot-resources/templates/700-nexus-ing.yaml
  jxboot-resources/templates/700-tide-ing.yaml
  jxboot-resources/values.yaml
Labels: approved, lgtm, ok-to-test, size/M

#37 fix: backword compat chartmuseum ingress
  jxboot-resources/templates/700-chartmuseum-ing.yaml
  jxboot-resources/values.yaml
Labels: approved, lgtm, size/S
